//
// Node Editor Version Info
//

#ifndef FLOWCV_EDITOR_UI_H_
#define FLOWCV_EDITOR_UI_H_

#ifndef EDITOR_UI_APP_VER
#define EDITOR_UI_APP_VER

#define FLOWCV_EDITOR_MAJOR_VERSION    0
#define FLOWCV_EDITOR_MINOR_VERSION    1
#define FLOWCV_EDITOR_PATCH_VERSION    3
#define FLOWCV_EDITOR_BUILD_VERSION    0

#define STRINGIFY(arg) #arg
#define VAR_ARG_STRING(arg) STRINGIFY(arg)

#define FLOWCV_EDITOR_VERSION  (((FLOWCV_EDITOR_MAJOR_VERSION) * 10000) + ((FLOWCV_EDITOR_MINOR_VERSION) * 100) + (FLOWCV_EDITOR_PATCH_VERSION))
/* Return version in "X.Y.Z" format */
#define FLOWCV_EDITOR_VERSION_STR (VAR_ARG_STRING(FLOWCV_EDITOR_MAJOR_VERSION.FLOWCV_EDITOR_MINOR_VERSION.FLOWCV_EDITOR_PATCH_VERSION))

#endif // End EDITOR_UI_APP_VER

#endif // FLOWCV_EDITOR_UI_H_
