//
// Internal Node Includes
//
#ifndef FLOWCV_INTERNAL_NODES_HPP_
#define FLOWCV_INTERNAL_NODES_HPP_
#include "Viewer/viewer.hpp"
#include "Blur/blur.hpp"
#include "Transform/transform.hpp"
#include "Canny/canny.hpp"
#include "HoughCircles/hough_circles.hpp"
#include "BlobDetector/blob_detector.hpp"
#include "JsonViewer/json_viewer.hpp"
#include "Morphology/Morphology.hpp"
#include "ConvertColor/convert_color.hpp"
#include "Threshold/threshold.hpp"
#include "Normalize/normalize.hpp"
#include "BackgroundSubtraction/background_subtraction.hpp"
#include "Bitwise/bitwise.hpp"
#include "Contours/contours.hpp"
#include "Crop/crop.hpp"
#include "Colorcorrect/ColorCorrect.hpp"
#include "DrawTools/draw_text.hpp"
#include "DrawTools/draw_number.hpp"
#include "DrawTools/draw_datetime.hpp"
#include "DrawTools/draw_json.hpp"
#include "Resize/resize.hpp"
#include "GetSize/get_size.hpp"
#include "GetOptimalDft/get_optimal_dft.hpp"
#include "CopyMakeBorder/copy_make_border.hpp"
#include "DiscreteFourierTransform/discrete_fourier_transform.hpp"
#include "Mean/mean.hpp"
#include "ScharrFilter/scharr_filter.hpp"
#include "ScaleAbs/scale_abs.hpp"
#include "AddWeighted/add_weighted.hpp"
#include "SobelFilter/sobel_filter.hpp"
#include "Magnitude/magnitude.hpp"
#include "LaplacianFilter/laplacian_filter.hpp"
#include "Add/add.hpp"
#include "AbsDiff/abs_diff.hpp"
#include "Divide/divide.hpp"
#include "Max/max.hpp"
#include "Min/min.hpp"
#include "Multiply/multiply.hpp"
#include "Subtract/subtract.hpp"
#include "RndNoise/rnd_noise.hpp"
#include "DiscreteCosineTransform/discrete_cosine_transform.hpp"
#include "HistogramViewer/histogram_viewer.hpp"
#include "ColorReduce/color_reduce.hpp"
#include "DepthViewer3d/depth_viewer_3D.hpp"
#include "HoughLines/hough_lines.hpp"
#include "Solid/solid.hpp"
#include "LineIntersect/line_intersect.hpp"
#include "PerspectiveWarp/perspective_warp.hpp"
#include "Sharpen/sharpen.hpp"


#endif //FLOWCV_INTERNAL_NODES_HPP_
