# OpenCV Configuration
if (WIN32)
    if (NOT OpenCV_DIR)
        set(OpenCV_DIR "${FLOWCV_PROJ_DIR}/third-party/opencv/build")
    endif()
endif()

message(STATUS "Adding OpenCV CMake Config")

FIND_PACKAGE( OpenCV )

if (NOT OPENCV_CORE_FOUND)
    message(WARNING "OpenCV Not Found")
    if (DOWNLOAD_OPENCV_PACKAGE)
        message(STATUS "Downloading OpenCV Package")
        if (WIN32)
            if (NOT "${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
                message(FATAL_ERROR "Only 64-bit supported on Windows")
            endif()
            file(DOWNLOAD https://github.com/opencv/opencv/releases/download/4.2.0/opencv-4.2.0-vc14_vc15.exe "${FLOWCV_PROJ_DIR}/third-party/opencv_4.2.0.zip")
            message(STATUS "Download Complete")
            message(STATUS "Extracting Files...")
            file(ARCHIVE_EXTRACT INPUT "${FLOWCV_PROJ_DIR}/third-party/opencv_4.2.0.zip" DESTINATION "${FLOWCV_PROJ_DIR}/third-party/")
            message(STATUS "Files Extracted")
            message(STATUS "Removing Archive")
            file(REMOVE "${FLOWCV_PROJ_DIR}/third-party/opencv_4.2.0.zip")
            message(STATUS "Sourcing Package")
            set(OpenCV_DIR "${FLOWCV_PROJ_DIR}/third-party/opencv/build")
            FIND_PACKAGE( OpenCV REQUIRED )
            file(COPY "${FLOWCV_PROJ_DIR}/third-party/opencv/build/x64/vc15/bin/opencv_world420.dll" DESTINATION "${CMAKE_BINARY_DIR}/")
        #if(APPLE)

        else()
            message(FATAL_ERROR "No OpenCV Detected Please Install OpenCV System Package")
        endif()
    endif()
endif()

if (OPENCV_CORE_FOUND)
    if (WIN32)
        if (CMAKE_BUILD_TYPE STREQUAL "Debug")
            file(COPY "${OpenCV_DIR}/x64/vc15/bin/opencv_world420d.dll" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")
            foreach(file_cv ${OpenCV_LIBS})
                list(APPEND OpenCV_Build_Libs "${OpenCV_DIR}x64/vc16/lib/${file_cv}420d.lib")
            endforeach()
        else()
            message(STATUS OpenCV Dir: ${OpenCV_DIR})
            file(COPY "${OpenCV_DIR}/x64/vc15/bin/opencv_world420.dll" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")
            foreach(file_cv ${OpenCV_LIBS})
                list(APPEND OpenCV_Build_Libs "${OpenCV_DIR}x64/vc16/lib/${file_cv}420.lib")
            endforeach()
        endif()
    endif()
endif()

INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})

