# OpenCV Configuration
if (WIN32)
    if (NOT OpenCV_DIR)
        set(OpenCV_DIR "${FLOWCV_PROJ_DIR}/third-party/opencv/build/cmake")
    endif()
endif()

message(STATUS "Adding OpenCV CMake Config")

FIND_PACKAGE( OpenCV )

if (NOT OPENCV_CORE_FOUND)
    message(WARNING "OpenCV Not Found")
    if (DOWNLOAD_OPENCV_PACKAGE)
        message(STATUS "Downloading OpenCV Package")
        if (WIN32)
            if (NOT "${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
                message(FATAL_ERROR "Only 64-bit supported on Windows")
            endif()
            file(DOWNLOAD https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2.zip "${FLOWCV_PROJ_DIR}/third-party/opencv_4.5.5.zip")
            message(STATUS "Download Complete")
            message(STATUS "Extracting Files...")
            file(ARCHIVE_EXTRACT INPUT "${FLOWCV_PROJ_DIR}/third-party/opencv_4.5.5.zip" DESTINATION "${FLOWCV_PROJ_DIR}/third-party/")
            message(STATUS "Files Extracted")
            message(STATUS "Removing Archive")
            file(REMOVE "${FLOWCV_PROJ_DIR}/third-party/opencv_4.5.5.zip")
            message(STATUS "Sourcing Package")
            set(OpenCV_DIR "${FLOWCV_PROJ_DIR}/third-party/opencv/build/cmake")
            FIND_PACKAGE( OpenCV REQUIRED PATHS ${OpenCV_DIR})
        #if(APPLE)

        else()
            message(FATAL_ERROR "No OpenCV Detected Please Install OpenCV System Package")
        endif()
    endif()
endif()

if (OPENCV_CORE_FOUND)
    if (WIN32)
        file(GLOB files "${OpenCV_DIR}/../bin/*.*")
        foreach(file_cv ${files})
            file(COPY "${file_cv}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")
        endforeach()
    endif()
endif()

INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})

