message(STATUS "Adding ImGUI GLFW CMake Config")

add_compile_definitions(IMGUI_DISABLE_DEMO_WINDOWS)

set(THIRD_PARTY_DIR ${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party)
set(IMGUI_DIR ${THIRD_PARTY_DIR}/imgui)

include_directories(${THIRD_PARTY_DIR})
include_directories(${IMGUI_DIR})
include_directories(${IMGUI_DIR}/backends)
list(APPEND IMGUI_SRC "${IMGUI_DIR}/imgui.cpp")
list(APPEND IMGUI_SRC "${IMGUI_DIR}/imgui_draw.cpp")
list(APPEND IMGUI_SRC "${IMGUI_DIR}/imgui_widgets.cpp")
list(APPEND IMGUI_SRC "${IMGUI_DIR}/imgui_tables.cpp")
list(APPEND IMGUI_SRC "${IMGUI_DIR}/backends/imgui_impl_glfw.cpp")
list(APPEND IMGUI_SRC "${IMGUI_DIR}/backends/imgui_impl_opengl3.cpp")

if (WIN32)
    add_compile_definitions(IMGUI_IMPL_OPENGL_LOADER_GLAD)
    set(_GLFW_Arch 32)
    if (${CMAKE_SIZEOF_VOID_P} EQUAL 8)
        set(_GLFW_Arch 64)
    endif()
    list(APPEND IMGUI_SRC "${THIRD_PARTY_DIR}/glad/glad.c")
    set(GLFW_DIR ${IMGUI_DIR}/examples/libs/glfw)
    include_directories("${GLFW_DIR}/include")
    list(APPEND IMGUI_LIBS "opengl32.lib")
    list(APPEND IMGUI_LIBS "gdi32.lib")
    list(APPEND IMGUI_LIBS "shell32.lib")
    list(APPEND IMGUI_LIBS "${GLFW_DIR}/lib-vc2019-${_GLFW_Arch}/glfw3.lib")
else()

    find_package(OpenGL REQUIRED)
    include_directories( ${OPENGL_INCLUDE_DIRS})

    find_package(glfw3 REQUIRED)
    include_directories(${GLFW_INCLUDE_DIRS})
    link_libraries(${GLFW_LIBRARY_DIRS})

    if (APPLE)
        add_compile_definitions(IMGUI_IMPL_OPENGL_LOADER_GLAD)
        find_library(COCOA_LIBRARY Cocoa)
        find_library(OpenGL_LIBRARY OpenGL)
        find_library(IOKIT_LIBRARY IOKit)
        find_library(COREVIDEO_LIBRARY CoreVideo)
        SET(IMGUI_EXTRA_LIBS ${COCOA_LIBRARY} ${OpenGL_LIBRARY} ${IOKIT_LIBRARY} ${COREVIDEO_LIBRARY})
        list(APPEND IMGUI_SRC "${THIRD_PARTY_DIR}/glad/glad.c")
        list(APPEND IMGUI_LIBS "glfw")
        list(APPEND IMGUI_LIBS "${OPENGL_LIBRARIES}")
        list(APPEND IMGUI_LIBS "${GLEW_LIBRARIES}")
        list(APPEND IMGUI_LIBS "${IMGUI_EXTRA_LIBS}")
    else()
        add_compile_definitions(IMGUI_IMPL_OPENGL_LOADER_GLAD)
        list(APPEND IMGUI_SRC "${THIRD_PARTY_DIR}/glad/glad.c")
        list(APPEND IMGUI_LIBS "dl")
        list(APPEND IMGUI_LIBS "glfw")
        list(APPEND IMGUI_LIBS "${OPENGL_LIBRARIES}")
        list(APPEND IMGUI_LIBS "${GLEW_LIBRARIES}")
    endif()

endif()
