# OpenCV Configuration
if (WIN32)
    if (NOT OpenCV_DIR)
        set(OpenCV_DIR "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/opencv/build/cmake")
    endif()
endif()

message(STATUS "Adding ImGUI OpenCV CMake Config")

FIND_PACKAGE( OpenCV )

if (NOT OPENCV_CORE_FOUND)
    message(WARNING "OpenCV Not Found")
    if (DOWNLOAD_OPENCV_PACKAGE)
        message(STATUS "Downloading OpenCV Package")
        if (WIN32)
            if (NOT "${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
                message(FATAL_ERROR "Only 64-bit supported on Windows")
            endif()
            if (CMAKE_BUILD_TYPE STREQUAL "Release")
                file(DOWNLOAD https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2.zip "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/opencv_4.5.5.zip")
                message(STATUS "Download Complete")
                message(STATUS "Extracting Files...")
                file(ARCHIVE_EXTRACT INPUT "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/opencv_4.5.5.zip" DESTINATION "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/")
                message(STATUS "Files Extracted")
                message(STATUS "Removing Archive")
                file(REMOVE "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/opencv_4.5.5.zip")
                message(STATUS "Sourcing Package")
                set(OpenCV_DIR "${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/opencv/build/cmake")
            endif()
            FIND_PACKAGE( OpenCV REQUIRED PATHS ${OpenCV_DIR})
        else()
            message(FATAL_ERROR "No OpenCV Detected Please Install OpenCV System Package")
        endif()
    endif()
endif()

if (OPENCV_CORE_FOUND)
    if (WIN32)
        file(GLOB files "${OpenCV_DIR}/../bin/*.*")
        foreach(file_cv ${files})
            file(COPY "${file_cv}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")
        endforeach()
    endif()
endif()

INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})

set(IMGUI_OPENCV_DIR ${CMAKE_SOURCE_DIR}/FlowCV_SDK/third-party/imgui_wrapper)
list(APPEND IMGUI_OPENCV_SRC "${IMGUI_OPENCV_DIR}/imgui_opencv.cpp")
